### ISSUE TITLE
The "RotationAxis" Issue

### ISSUE THREAD

**Issue by hippieZhou** [JuniperPhoton/FlipperControl#2]
Hi, JuniperPhoton,When I use your Test Sample Code in my black project ,There is an exception:

![Snipaste_2019-04-30_10-02-41](https://user-images.githubusercontent.com/13598361/56937435-33e82e80-6b2f-11e9-92bf-85f540140f70.png)
![Snipaste_2019-04-30_10-02-59](https://user-images.githubusercontent.com/13598361/56937437-33e82e80-6b2f-11e9-8a2a-37521456b968.png)

But When I remove 

```XAML
RotationAxis="X"
```
It can running well.

**Comment by JuniperPhoton** [comment]
Please try this: move your cursor over the `FlipperControl` and press F12, which will go to see the defination of `FlipperLayout`.

Check if there is a property named `RotationAxis` or attach the screenshot in this issue.

**Comment by hippieZhou** [comment]
I use it from NuGet, as followed:
<img width="567" alt="Snipaste_2019-05-01_20-43-19" src="https://user-images.githubusercontent.com/13598361/57017436-d3054700-6c51-11e9-9020-01fe5329938d.png">

<img width="615" alt="Snipaste_2019-05-01_20-46-14" src="https://user-images.githubusercontent.com/13598361/57017548-38593800-6c52-11e9-93a4-3100b5b7b7c5.png">

your  FlipperControl Inherited from **UIElement**，but UIElement has the same prop **RotationAxis**,and their **type** are different. maybe this is not a better way .

<img width="1182" alt="Snipaste_2019-05-01_20-57-08" src="https://user-images.githubusercontent.com/13598361/57017893-c08c0d00-6c53-11e9-8181-5972e1a8575c.png">

**Comment by JuniperPhoton** [comment]
I found that this property is added in 1809...I would rename this property later.
Currently you can try adding namespace to this property and see if this can solve the issue.

**Comment by JuniperPhoton** [comment]
@hippieZhou Please try to upgrade to the 1.0.8 version and try again :)
